name: Create a New Issue
description: 새로운 이슈를 생성하기 위한 템플릿입니다.
body:
  - type: input
    id: issue_description
    attributes:
      label: 이슈 설명
      description: 이슈에 대해 설명해주세요.
      placeholder: 간략히~
    validations:
      required: true
  - type: textarea
    id: issue_detail
    attributes:
      label: 상세 내용
      description: 이슈의 내용을 상세히 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: issue_worklist
    attributes:
      label: 작업 목록
      description: 이슈에 필요한 작업 목록을 작성해주세요.
      value: |
        - [ ] 필요한 작업 내용
    validations:
      required: true
  - type: input
    id: design_doc
    attributes:
      label: 디자인 문서
      description: 이 이슈룰 위한 디자인 문서(링크)가 있다면 추가해주세요.
  - type: input
    id: tracking_issues
    attributes:
      label: 관련 이슈 or 참고 자료
      description: 이 기능과 관련된 이슈나 참고할 자료가 있다면 추가해주세요.
